#! /usr/bin/env python
import sys
import os

# Scan the download directory for all torrent files
# return found torrent files
def scan_for_torrents(folder):
    ret = []

    for file in os.listdir(folder):
        if file.endswith(".torrent"):
            ret.append(file)

    return ret

# Move a found file from scanned folder to 
# destination folder
def move_file(scanf, destf, file):
    os.rename(scanf + '/' + file, destf + '/' + file)

# Main func to run program
# Arg 1: Download directory to scan 
# Arg 2: Destination directory to move file to
# print sys.argv
def main():
    SCANF = sys.argv[1]
    DESTF = sys.argv[2]
    found_files = scan_for_torrents(SCANF)

    for file in found_files:
        move_file(SCANF, DESTF, file)

main()